---
title: "use_recipes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{use_recipes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(metaSurvey)

set_engine()

svy_example = load_survey(
    svy_type = "eaii",
    svy_edition = "2019-2021",
    svy_weight = "w_trans",
    input = load_survey_example("2019-2021.csv"),
    dec = ","
)

# as.data.frame(svy_example)
# as.tibble(svy_example)

new_svy = svy_example %>%
    step_recode(
        new_var = "realiza_innovacion",
        B1_1_1 == 1 ~ 1,
        B1_2_1 == 1 ~ 1,
        B1_3_1 == 1 ~ 1,
        B1_4_1 == 1 ~ 1,
        B1_5_1 == 1 ~ 1,
        B1_6_1 == 1 ~ 1,
        B1_7_1 == 1 ~ 1,
        B1_8_1 == 1 ~ 1,
        B1_9_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "sector",
        data.table::between(Division, 10, 33) ~ "Industria",
        data.table::between(Division, 34, 99) ~ "Servicios",
        Division == "C1" ~ "Industria",
        Division == "C2" ~ "Servicios",
        Division == "E1" ~ "Servicios"
    ) %>%
    step_recode(
        new_var = "innovativa",
        E1_1_1 == 1 ~ 1,
        E1_2_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "realiza_id_interna",
        B1_1_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "realiza_id_externa",
        B1_2_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "realiza_bienescapital",
        B1_3_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "realiza_software",
        B1_4_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "realiza_propiedadintelectual",
        B1_5_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "realiza_ingenieria",
        B1_6_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "realiza_capacitacion",
        B1_7_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "realiza_marketing",
        B1_8_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "realiza_gestion",
        B1_9_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "innova_producto",
        E1_1_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "innova_proceso",
        E1_2_1 == 1 ~ 1,
        .default = 0
    ) %>%
    step_recode(
        new_var = "cant_traba_tramo",
        data.table::between(IG_4_1_3, 0, 4) ~ "1",
        data.table::between(IG_4_1_3, 5, 19) ~ "2",
        data.table::between(IG_4_1_3, 20, 99) ~ "3",
        IG_4_1_3 > 99 ~ "4"
    ) %>%
    step_recode(
        new_var = "ingreso_vta_pesos",
        data.table::between(IG_5_1_1_3, 0, 9942787) ~ "1",
        data.table::between(IG_5_1_1_3, 9942788, 49713934) ~ "2", # nolint
        data.table::between(IG_5_1_1_3, 49713935, 372854507) ~ "3", # nolint
        IG_5_1_1_3 > 372854507 ~ "4"
    ) %>%
    step_recode(
        new_var = "tamanio",
        cant_traba_tramo == "1" & ingreso_vta_pesos == "1" ~ "Pequenias",
        cant_traba_tramo == "2" & ingreso_vta_pesos == "2" ~ "Pequenias",
        cant_traba_tramo == "2" & ingreso_vta_pesos == "1" ~ "Pequenias",
        cant_traba_tramo == "1" & ingreso_vta_pesos == "2" ~ "Pequenias",
        cant_traba_tramo == "3" & ingreso_vta_pesos == "3" ~ "Medianas",
        cant_traba_tramo == "3" & ingreso_vta_pesos == "2" ~ "Medianas",
        cant_traba_tramo == "3" & ingreso_vta_pesos == "1" ~ "Medianas",
        cant_traba_tramo == "1" & ingreso_vta_pesos == "3" ~ "Medianas",
        cant_traba_tramo == "2" & ingreso_vta_pesos == "3" ~ "Medianas",
        cant_traba_tramo == "4" & ingreso_vta_pesos == "4" ~ "Grandes",
        cant_traba_tramo == "4" & ingreso_vta_pesos == "3" ~ "Grandes",
        cant_traba_tramo == "4" & ingreso_vta_pesos == "2" ~ "Grandes",
        cant_traba_tramo == "4" & ingreso_vta_pesos == "1" ~ "Grandes",
        cant_traba_tramo == "1" & ingreso_vta_pesos == "4" ~ "Grandes",
        cant_traba_tramo == "2" & ingreso_vta_pesos == "4" ~ "Grandes",
        cant_traba_tramo == "3" & ingreso_vta_pesos == "4" ~ "Grandes"
    ) %>%
    step_compute(
        subsector = Division
    )

get_metadata(new_svy)

# Ver steps 

steps = get_steps(new_svy)

```


# Introduction






# Coherción



# Ejemplo de steps (no toca el objeto original)


# Ver metadatos


